"""extend ai_reports with risk_level findings observations

Revision ID: 0e40bbb58783
Revises: 202882577f8f
Create Date: 2026-05-30 09:45:36.151725
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e40bbb58783'
down_revision: Union[str, None] = '202882577f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_reports', sa.Column('risk_level', sa.Text(), nullable=True))
    op.add_column('ai_reports', sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_reports', sa.Column('security_observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_reports', sa.Column('performance_observations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_reports', 'performance_observations')
    op.drop_column('ai_reports', 'security_observations')
    op.drop_column('ai_reports', 'key_findings')
    op.drop_column('ai_reports', 'risk_level')
    # ### end Alembic commands ###
