"""add logs table

Revision ID: 202882577f8f
Revises: 4980a9791eb1
Create Date: 2026-05-30 09:44:47.006353
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202882577f8f'
down_revision: Union[str, None] = '4980a9791eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('log_source', sa.String(length=50), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('parsed_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_collected_at'), 'logs', ['collected_at'], unique=False)
    op.create_index(op.f('ix_logs_log_level'), 'logs', ['log_level'], unique=False)
    op.create_index(op.f('ix_logs_log_source'), 'logs', ['log_source'], unique=False)
    op.create_index(op.f('ix_logs_server_id'), 'logs', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_server_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_source'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_collected_at'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
