"""add pending_actions table

Revision ID: 7beef988507e
Revises: 0e40bbb58783
Create Date: 2026-05-30 10:06:42.302188
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beef988507e'
down_revision: Union[str, None] = '0e40bbb58783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('confirmed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('command_key', sa.String(length=100), nullable=False),
    sa.Column('command_string', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'awaiting_second_confirmation', 'approved', 'executing', 'completed', 'cancelled', 'expired', name='action_status'), nullable=False),
    sa.Column('dry_run_output', sa.Text(), nullable=True),
    sa.Column('execution_output', sa.Text(), nullable=True),
    sa.Column('password_verified', sa.Boolean(), nullable=False),
    sa.Column('second_confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('second_confirmation_received', sa.Boolean(), nullable=False),
    sa.Column('time_lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_created_at'), 'pending_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pending_actions_expires_at'), 'pending_actions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pending_actions_requested_by_user_id'), 'pending_actions', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_risk_level'), 'pending_actions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_pending_actions_server_id'), 'pending_actions', ['server_id'], unique=False)
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_server_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_risk_level'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_requested_by_user_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_expires_at'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_created_at'), table_name='pending_actions')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
