"""add force_password_change and security_scans

Revision ID: ae83496b62d6
Revises: 7beef988507e
Create Date: 2026-05-30 11:17:35.748517
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae83496b62d6'
down_revision: Union[str, None] = '7beef988507e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('scan_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('critical_findings', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scanned_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scanned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_scans_scanned_at'), 'security_scans', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_security_scans_server_id'), 'security_scans', ['server_id'], unique=False)
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    op.drop_index(op.f('ix_security_scans_server_id'), table_name='security_scans')
    op.drop_index(op.f('ix_security_scans_scanned_at'), table_name='security_scans')
    op.drop_table('security_scans')
    # ### end Alembic commands ###
